### ISSUE TITLE
GLIGEN checkpoint not match

### ISSUE THREAD

**Issue by J-Yuhao** [weixi-feng/LayoutGPT#10]
Hi, 
I'm running into this issue in the layout to image step:

Traceback (most recent call last):File "/mnt/LayoutGPT/gligen/gligen layout counting.py", line 427, in <module>main(args)
File "/mnt/LayoutGPT/gligen/gligen layout counting.py", line 410, in _mainrun(meta list, args, starting noise)File "/root/miniconda3/envs/myconda/lib/python3.9/site-packages/torch/utils/ contextlib.py", line 115, in decorate contextreturn func(*args，**kwargs)File "/mnt/LayoutGpT/gligen/gligen layout counting.py", line 282, in run
model, autoencoder, text encoder, diffusion, config = load ckpt(metar"ckpt"])
File "/mnt/LayoutGPT/gligen/gligen layout counting.py", line 85, in load ckpttext encoder.load state dict( saved ckptr"text encoder"File "/root/miniconda3/envs/myconda/lib/python3.9/site-packapes/torch/mn/modules/module,py", line 2041, in load state dictraise RuntimeError('Error(s) in loading state dict for :nlt'.format(RuntimeError: Error(s) in loading state dict for FrozenCLIPEmbedder:
Unexpected kev(s) in state dict:
"transformer.text model.embeddings .position ids"

I'm sure I used the right GLIGEN checkpoint as instructed, but not able to figure out why there were unexpected keys.

**Comment by samsara-ku** [comment]
I don't know what is exactly going on the diffusers repository, but I found that there is no need to loading "transformer.text_model.embeddings.position_ids" to the text_encoder in the version of `openai/clip-vit-large-patch14`.

So you just choose one of below:

First, I just remove the key value of "transformer.text_model.embeddings.position_ids" in the checkpoint because I just want to ensure successful key matching of text_encoder like this:
`del saved_ckpt["text_encoder"]["transformer.text_model.embeddings.position_ids"]`

Or, you just use the `strict` option of load_checkpoint as False for easier checkpoint loading like this:
`text_encoder.load_state_dict( saved_ckpt["text_encoder"], strict=False)`
