### ISSUE TITLE
No such file or directory: 'gligen_checkpoints/checkpoint_generation_text.pth'

### ISSUE THREAD

**Issue by huangpan2507** [weixi-feng/LayoutGPT#12]
2D Image Layout Generation

The generated layout will be saved to ./llm_output/counting by default. To generate images based on the layouts, run

`(layoutgpt) ubuntu@host13:~/nj/text-3d/LayoutGPT/gligen$ python gligen_layout_counting.py --file ../llm_output/counting/gpt4.counting.         k-similar.k_8.px_64.json --batch_size 5

Images will be saved at ./generation_samples/counting/gpt4.counting.k-similar.k_8.px_64
Traceback (most recent call last):
  File "gligen_layout_counting.py", line 427, in <module>
    _main(args)
  File "gligen_layout_counting.py", line 410, in _main
    run(meta_list, args, starting_noise)
  File "/home/ubuntu/anaconda3/envs/layoutgpt/lib/python3.8/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "gligen_layout_counting.py", line 282, in run
    model, autoencoder, text_encoder, diffusion, config = load_ckpt(meta["ckpt"])
  File "gligen_layout_counting.py", line 74, in load_ckpt
    saved_ckpt = torch.load(ckpt_path)
  File "/home/ubuntu/anaconda3/envs/layoutgpt/lib/python3.8/site-packages/torch/serialization.py", line 791, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "/home/ubuntu/anaconda3/envs/layoutgpt/lib/python3.8/site-packages/torch/serialization.py", line 271, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "/home/ubuntu/anaconda3/envs/layoutgpt/lib/python3.8/site-packages/torch/serialization.py", line 252, in __init__
    super().__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: 'gligen_checkpoints/checkpoint_generation_text.pth'
`

No such file or directory: 'gligen_checkpoints/checkpoint_generation_text.pth'

For GLIGEN, download the [Box+Text](https://github.com/gligen/GLIGEN/tree/master#download-gligen-models) checkpoint and put it under gligen/gligen_checkpoints, so I can download diffusion_pytorch_model.bin under that website.
But I cann't find which step do this job(downloading checkpoint_generation_text.pth), can you help me?

**Comment by samsara-ku** [comment]
https://github.com/gligen/GLIGEN/issues/13

Just change the `diffusion_pytorch_model.bin` as `checkpoint_generation_text.pth`

**Comment by weixi-feng** [comment]
Thanks a lot @samsara-ku. Closing the issue now.
